FROM node:18-alpine

RUN npm install -g npm@latest

RUN apk add --no-cache libc6-compat

RUN apk update && apk add git

RUN mkdir -p /admin

RUN mkdir -p /upload

RUN mkdir -p ./logs/npm:/root/.npm/_logs

WORKDIR /admin

COPY ["package.json", "./"]

COPY ["package-lock.json", "./"]

COPY ["*/package.json", "./"]

RUN npm i --omit=dev

COPY [".", "."]

EXPOSE 1337

CMD turbo run start --scope=admin