version: "3.8"
services:
  certbot:
    container_name: certbot
    build: _helpers/certbot
    volumes:
      - ./logs/letsencrypt:/var/log/letsencrypt
      - certbot_certs:/etc/letsencrypt
      - certbot:/var/www/certbot
    links:
      - nginx
  cron:
    container_name: cron
    build: _helpers/cron
    volumes:
      - ./logs/cron:/var/log/cron
      - ./logs/letsencrypt:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
      - certbot_certs:/etc/letsencrypt
      - certbot:/var/www/certbot
    links:
      - certbot
      - nginx
    restart: always
  nginx:
    container_name: nginx
    build: _helpers/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - nginx_ssl:/etc/nginx/ssl
      - certbot_certs:/etc/letsencrypt
      - certbot:/var/www/certbot
    restart: always
    links:
      - admin
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile.Admin
    restart: always
    ports:
      - 1337:1337
    volumes:
      - ./:/admin
      - /admin/node_modules
      - /admin/apps/admin/node_modules
      - /admin/apps/store/node_modules
      - /upload:/admin/upload
      - ./logs/npm:/root/.npm/_logs
    env_file:
      - ./apps/admin/.env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
    env_file:
      - ./.env
volumes:
  nginx_ssl: {}
  certbot_certs: {}
  certbot: {}
